waitUntil {alive player};
player removeAction (player getVariable "_uav_action");
player setvariable ["_uav_action", nil];
player removeAction (player getVariable "_uav_heli_action");
player setvariable ["_uav_heli_action", nil];
player removeAction (player getVariable "_teleport_action");
player setvariable ["_teleport_action",nil];
player removeAction (player getVariable "_join_grpNull");
player setvariable ["_join_grpNull",nil];
player removeAction (player getVariable "_Buy_Menu");
player setvariable ["_Buy_Menu",nil];
player removeAction (player getVariable "_teleport_action");
player setvariable ["_teleport_action",nil];
player removeAction (player getVariable "_menu_action");
player setvariable ["_menu_action",nil];
player removeAction (player getVariable "_coin");
player setvariable ["_coin",nil];
