// nato_usmc_d
[
// configName "rhs_group_nato_usmc_d_infantry_squad",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman","rhsusf_usmc_marpat_d_rifleman_m4","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4","rhsusf_usmc_marpat_d_riflemanat","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4","rhsusf_usmc_marpat_d_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0],[17,0,0],[19,0,0],[21,0,0],[23,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_infantry_weaponsquad",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner","rhsusf_usmc_marpat_d_machinegunner_ass","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner","rhsusf_usmc_marpat_d_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","CORPORAL","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_infantry_squad_sniper",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter","rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter","rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_infantry_team",
[[[["rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4","rhsusf_usmc_marpat_d_riflemanat"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_infantry_team_MG",
[[[["rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner","rhsusf_usmc_marpat_d_machinegunner_ass","rhsusf_usmc_marpat_d_rifleman_m4"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_infantry_team_AA",
[[[["rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4","rhsusf_usmc_marpat_d_stinger"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_infantry_team_support",
[[[["rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4","rhsusf_navy_marpat_d_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_infantry_team_heavy_AT",
[[[["rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4","rhsusf_usmc_marpat_d_javelin"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_recon_d_infantry_team",
[[[["rhsusf_usmc_recon_marpat_d_teamleader","rhsusf_usmc_recon_marpat_d_marksman","rhsusf_usmc_recon_marpat_d_autorifleman","rhsusf_usmc_recon_marpat_d_rifleman_at","rhsusf_usmc_recon_marpat_d_rifleman","rhsusf_usmc_recon_marpat_d_machinegunner_m249"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_nato_usmc_recon_d_infantry_team_MG",
[[[["rhsusf_usmc_recon_marpat_d_teamleader","rhsusf_usmc_recon_marpat_d_marksman","rhsusf_usmc_recon_marpat_d_autorifleman","rhsusf_usmc_recon_marpat_d_rifleman_at","rhsusf_usmc_recon_marpat_d_rifleman","rhsusf_usmc_recon_marpat_d_machinegunner"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_nato_usmc_recon_d_infantry_team_support",
[[[["rhsusf_usmc_recon_marpat_d_teamleader","rhsusf_usmc_recon_marpat_d_marksman","rhsusf_usmc_recon_marpat_d_autorifleman","rhsusf_navy_sarc_d","rhsusf_usmc_recon_marpat_d_rifleman","rhsusf_usmc_recon_marpat_d_machinegunner_m249"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_nato_usmc_recon_d_infantry_team_lite",
[[[["rhsusf_usmc_recon_marpat_d_teamleader_lite","rhsusf_usmc_recon_marpat_d_marksman_lite","rhsusf_usmc_recon_marpat_d_autorifleman_lite","rhsusf_usmc_recon_marpat_d_rifleman_at_lite","rhsusf_usmc_recon_marpat_d_rifleman_lite","rhsusf_usmc_recon_marpat_d_machinegunner_m249_lite"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_nato_usmc_recon_d_infantry_team_fast",
[[[["rhsusf_usmc_recon_marpat_d_teamleader_fast","rhsusf_usmc_recon_marpat_d_marksman_fast","rhsusf_usmc_recon_marpat_d_autorifleman_fast","rhsusf_usmc_recon_marpat_d_rifleman_at_fast","rhsusf_usmc_recon_marpat_d_rifleman_fast","rhsusf_usmc_recon_marpat_d_machinegunner_m249_fast"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_nato_usmc_d_RG33_squad",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_rg33_usmc_d","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_riflemanat","rhsusf_usmc_marpat_d_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_RG33_squad_2mg",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner","rhsusf_rg33_usmc_d","rhsusf_usmc_marpat_d_machinegunner_ass","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner","rhsusf_usmc_marpat_d_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_RG33_squad_sniper",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper","rhsusf_rg33_usmc_d","rhsusf_usmc_marpat_d_spotter","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_RG33_squad_mg_sniper",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_army_ocp_teamleader","rhsusf_usmc_marpat_d_machinegunner","rhsusf_rg33_usmc_d","rhsusf_usmc_marpat_d_machinegunner_ass","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_RG33_m2_squad",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_rg33_m2_usmc_d","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_riflemanat","rhsusf_usmc_marpat_d_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_RG33_m2_squad_2mg",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner","rhsusf_rg33_m2_usmc_d","rhsusf_usmc_marpat_d_machinegunner_ass","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner","rhsusf_usmc_marpat_d_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_RG33_m2_squad_sniper",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman","rhsusf_rg33_m2_usmc_d","rhsusf_usmc_marpat_d_spotter","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_d_RG33_m2_squad_mg_sniper",
[[[["rhsusf_usmc_marpat_d_squadleader","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner","rhsusf_rg33_m2_usmc_d","rhsusf_usmc_marpat_d_machinegunner_ass","rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "BUS_MotInf_Team_GMG",
[[[["rhsusf_m1025_d_s_Mk19","rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_riflemanat","rhsusf_usmc_marpat_d_rifleman"],[[0,0,0],[-12,-12,0],[14,-13,0],[5,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL"]]],0],
// configName "BUS_MotInf_Team_HMG",
[[[["rhsusf_m1025_d_s_m2","rhsusf_usmc_marpat_d_rifleman","rhsusf_usmc_marpat_d_riflemanat","rhsusf_usmc_marpat_d_rifleman"],[[0,0,0],[-12,-12,0],[14,-13,0],[5,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL"]]],0],
// configName "BUS_MotInf_AT",
[[[["rhsusf_m1025_d_s","rhsusf_usmc_marpat_d_rifleman","rhsusf_usmc_marpat_d_javelin","rhsusf_usmc_marpat_d_javelin"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],["SERGEANT","CORPORAL","CORPORAL","PRIVATE"]]],0],
// configName "BUS_MotInf_AA",
[[[["rhsusf_m1025_d_s","rhsusf_usmc_marpat_d_rifleman","rhsusf_usmc_marpat_d_stinger","rhsusf_usmc_marpat_d_stinger"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],["SERGEANT","CORPORAL","CORPORAL","PRIVATE"]]],0],
// configName "RHS_M1A1AIM_d_Platoon",
[[[["rhsusf_m1a1fep_d","rhsusf_m1a1fep_d","rhsusf_m1a1fep_d","rhsusf_m1a1fep_d"],[[0,0,0],[-20,-30,3],[20,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0],
// configName "RHS_M1A1FEP_d_Section",
[[[["rhsusf_m1a1fep_d","rhsusf_m1a1fep_d"],[[0,0,0],[-20,-30,2]],["LIEUTENANT","SERGEANT"]]],0]
];

// nato_usmc_wd
[
// configName "rhs_group_nato_usmc_wd_infantry_squad",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_riflemanat","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0],[17,0,0],[19,0,0],[21,0,0],[23,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_infantry_weaponsquad",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner","rhsusf_usmc_marpat_wd_machinegunner_ass","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner","rhsusf_usmc_marpat_wd_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","CORPORAL","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_infantry_squad_sniper",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter","rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter","rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_infantry_team",
[[[["rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_riflemanat"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_infantry_team_MG",
[[[["rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner","rhsusf_usmc_marpat_wd_machinegunner_ass","rhsusf_usmc_marpat_wd_rifleman_m4"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_infantry_team_AA",
[[[["rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_stinger"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_infantry_team_support",
[[[["rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_navy_marpat_wd_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_infantry_team_heavy_AT",
[[[["rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_javelin"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_recon_wd_infantry_team",
[[[["rhsusf_usmc_recon_marpat_wd_teamleader","rhsusf_usmc_recon_marpat_wd_marksman","rhsusf_usmc_recon_marpat_wd_autorifleman","rhsusf_usmc_recon_marpat_wd_rifleman_at","rhsusf_usmc_recon_marpat_wd_rifleman","rhsusf_usmc_recon_marpat_wd_machinegunner_m249"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_nato_usmc_recon_wd_infantry_team_MG",
[[[["rhsusf_usmc_recon_marpat_wd_teamleader","rhsusf_usmc_recon_marpat_wd_marksman","rhsusf_usmc_recon_marpat_wd_autorifleman","rhsusf_usmc_recon_marpat_wd_rifleman_at","rhsusf_usmc_recon_marpat_wd_rifleman","rhsusf_usmc_recon_marpat_wd_machinegunner"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_nato_usmc_recon_wd_infantry_team_support",
[[[["rhsusf_usmc_recon_marpat_wd_teamleader","rhsusf_usmc_recon_marpat_wd_marksman","rhsusf_usmc_recon_marpat_wd_autorifleman","rhsusf_navy_sarc_w","rhsusf_usmc_recon_marpat_wd_rifleman","rhsusf_usmc_recon_marpat_wd_machinegunner_m249"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_nato_usmc_recon_wd_infantry_team_lite",
[[[["rhsusf_usmc_recon_marpat_wd_teamleader_lite","rhsusf_usmc_recon_marpat_wd_marksman_lite","rhsusf_usmc_recon_marpat_wd_autorifleman_lite","rhsusf_usmc_recon_marpat_wd_rifleman_at_lite","rhsusf_usmc_recon_marpat_wd_rifleman_lite","rhsusf_usmc_recon_marpat_wd_machinegunner_m249_lite"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_nato_usmc_recon_wd_infantry_team_fast",
[[[["rhsusf_usmc_recon_marpat_wd_teamleader_fast","rhsusf_usmc_recon_marpat_wd_marksman_fast","rhsusf_usmc_recon_marpat_wd_autorifleman_fast","rhsusf_usmc_recon_marpat_wd_rifleman_at_fast","rhsusf_usmc_recon_marpat_wd_rifleman_fast","rhsusf_usmc_recon_marpat_wd_machinegunner_m249_fast"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["SERGEANT","SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
// configName "BUS_MotInf_Team_GMG",
[[[["rhsusf_m1025_w_s_Mk19","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_riflemanat","rhsusf_usmc_marpat_wd_rifleman"],[[0,0,0],[-12,-12,0],[14,-13,0],[5,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL"]]],0],
// configName "BUS_MotInf_Team_HMG",
[[[["rhsusf_m1025_w_s_m2","rhsusf_usmc_marpat_wd_rifleman","rhsusf_usmc_marpat_wd_riflemanat","rhsusf_usmc_marpat_wd_rifleman"],[[0,0,0],[-12,-12,0],[14,-13,0],[5,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL"]]],0],
// configName "BUS_MotInf_AT",
[[[["rhsusf_m1025_w_s","rhsusf_usmc_marpat_wd_rifleman","rhsusf_usmc_marpat_wd_javelin","rhsusf_usmc_marpat_wd_javelin"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],["SERGEANT","CORPORAL","CORPORAL","PRIVATE"]]],0],
// configName "BUS_MotInf_AA",
[[[["rhsusf_m1025_w_s","rhsusf_usmc_marpat_wd_rifleman","rhsusf_usmc_marpat_wd_stinger","rhsusf_usmc_marpat_wd_stinger"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],["SERGEANT","CORPORAL","CORPORAL","PRIVATE"]]],0],
// configName "rhs_group_nato_usmc_wd_RG33_squad",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_rg33_usmc_wd","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_riflemanat","rhsusf_usmc_marpat_wd_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_RG33_squad_2mg",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner","rhsusf_rg33_usmc_wd","rhsusf_usmc_marpat_wd_machinegunner_ass","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner","rhsusf_usmc_marpat_wd_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_RG33_squad_sniper",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper","rhsusf_rg33_usmc_wd","rhsusf_usmc_marpat_wd_spotter","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_RG33_squad_mg_sniper",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_army_ocp_teamleader","rhsusf_usmc_marpat_wd_machinegunner","rhsusf_rg33_usmc_wd","rhsusf_usmc_marpat_wd_machinegunner_ass","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_RG33_m2_squad",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_rg33_m2_usmc_wd","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_riflemanat","rhsusf_usmc_marpat_wd_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_RG33_m2_squad_2mg",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner","rhsusf_rg33_m2_usmc_wd","rhsusf_usmc_marpat_wd_machinegunner_ass","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner","rhsusf_usmc_marpat_wd_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_RG33_m2_squad_sniper",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman","rhsusf_rg33_m2_usmc_wd","rhsusf_usmc_marpat_wd_spotter","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_nato_usmc_wd_RG33_m2_squad_mg_sniper",
[[[["rhsusf_usmc_marpat_wd_squadleader","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner","rhsusf_rg33_m2_usmc_wd","rhsusf_usmc_marpat_wd_machinegunner_ass","rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "RHS_M1A1AIM_wd_Platoon",
[[[["rhsusf_m1a1fep_wd","rhsusf_m1a1fep_wd","rhsusf_m1a1fep_wd","rhsusf_m1a1fep_wd"],[[0,0,0],[-20,-30,3],[20,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0],
// configName "RHS_M1A1FEP_wd_Section",
[[[["rhsusf_m1a1fep_wd","rhsusf_m1a1fep_wd"],[[0,0,0],[-20,-30,2]],["LIEUTENANT","SERGEANT"]]],0]
];
