// OPF_F orig
_east=_east+[
	// OIA_SPGPlatoon_Scorcher
	[[[["O_MBT_02_arty_F",
		"O_MBT_02_arty_F","O_MBT_02_arty_F",
		"O_MBT_02_arty_F"],[[0,0,0],[10,-10,0],[-10,-10,0],[20,-20,0]],
		["LIEUTENANT",
		"SERGEANT","SERGEANT",
		"CORPORAL"]]],0],
	// OIA_SPGSection_Scorcher
	[[[["O_MBT_02_arty_F","O_MBT_02_arty_F"],[[0,0,0],[10,-10,0]],
		["LIEUTENANT","SERGEANT"]]],0],
	// OIA_InfSquad
	[[[["O_soldier_SL_F",
		"O_soldier_F","O_soldier_LAT_F",
		"O_soldier_M_F","O_soldier_TL_F",
		"O_soldier_AR_F","O_soldier_A_F",
		"O_medic_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0],[-10,-10,0],[15,-15,0],[-15,-15,0],[20,-20,0]],
		["SERGEANT",
		"PRIVATE","CORPORAL",
		"PRIVATE","SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0],
	// OIA_InfSquad_Weapons
	[[[["O_soldier_SL_F",
		"O_soldier_AR_F","O_soldier_GL_F",
		"O_soldier_M_F","O_soldier_AT_F",
		"O_soldier_AAT_F","O_soldier_A_F",
		"O_medic_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0],[-10,-10,0],[15,-15,0],[-15,-15,0],[20,-20,0]],
		["SERGEANT",
		"PRIVATE","CORPORAL",
		"SERGEANT","CORPORAL",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0],
	// OIA_InfTeam
	[[[["O_soldier_TL_F",
		"O_soldier_AR_F","O_soldier_GL_F",
		"O_soldier_LAT_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0],
	// OIA_InfTeam_AT
	[[[["O_soldier_TL_F",
		"O_soldier_AT_F","O_soldier_AT_F",
		"O_soldier_AAT_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0],
	// OIA_InfTeam_AA
	[[[["O_soldier_TL_F",
		"O_soldier_AA_F","O_soldier_AA_F",
		"O_soldier_AAA_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0],
	// OIA_InfSentry
	[[[["O_soldier_GL_F","O_soldier_F"],[[0,0,0],[5,-2,0]],
		["CORPORAL","PRIVATE"]]],0],
	// OI_reconTeam
	[[[["O_recon_TL_F",
		"O_recon_M_F","O_recon_medic_F",
		"O_recon_LAT_F","O_recon_JTAC_F",
		"O_recon_exp_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0],[-10,-10,0],[15,-15,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0],
	// OI_reconPatrol
	[[[["O_recon_TL_F",
		"O_recon_M_F","O_recon_medic_F",
		"O_recon_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0],
	// OI_reconSentry
	[[[["O_recon_M_F","O_recon_F"],[[0,0,0],[5,-5,0]],
		["CORPORAL","PRIVATE"]]],0],
	// OI_SniperTeam
	[[[["O_sniper_F","O_spotter_F"],[[0,0,0],[5,-5,0]],
		["CORPORAL","PRIVATE"]]],0],
	// OIA_InfAssault
	[[[["O_Soldier_SL_F",
		"O_Soldier_AR_F","O_HeavyGunner_F",
		"O_Soldier_AAR_F","O_soldier_M_F",
		"O_Sharpshooter_F","O_Soldier_LAT_F",
		"O_medic_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0],[-10,-10,0],[15,-15,0],[-15,-15,0],[20,-20,0]],
		["SERGEANT",
		"PRIVATE","CORPORAL",
		"PRIVATE","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0],
	// OIA_ReconSquad
	[[[["O_recon_TL_F",
		"O_recon_M_F","O_recon_medic_F",
		"O_recon_F","O_recon_LAT_F",
		"O_recon_JTAC_F","O_recon_exp_F",
		"O_Pathfinder_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0],[-10,-10,0],[15,-15,0],[-15,-15,0],[20,-20,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"CORPORAL"]]],0],
	// O_InfTeam_AT_Heavy
	[[[["O_soldier_TL_F",
		"O_soldier_HAT_F","O_soldier_HAT_F",
		"O_soldier_AHAT_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0],
	// OI_diverTeam
	[[[["O_diver_TL_F",
		"O_diver_exp_F","O_diver_F",
		"O_diver_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0],
	// OI_diverTeam_Boat
	[[[["O_diver_TL_F",
		"O_diver_exp_F","O_diver_F",
		"O_diver_F","O_Boat_Transport_01_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0],[-10,-10,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0],
	// OI_diverTeam_SDV
	[[[["O_diver_TL_F",
		"O_diver_exp_F","O_diver_F",
		"O_diver_F","O_SDV_01_F",
		"O_SDV_01_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0],[-10,-10,0],[15,-15,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0],
	// OI_SmallTeam_UAV
	[[[["O_soldier_TL_F",
		"O_soldier_UAV_F","O_UAV_01_F"],[[0,0,0],[5,-5,0],[-5,-5,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE"]]],0],
	// OI_ReconTeam_UGV
	[[[["O_soldier_TL_F",
		"O_soldier_UAV_F","O_UGV_01_F"],[[0,0,0],[5,-5,0],[-5,-5,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE"]]],0],
	// OI_AttackTeam_UGV
	[[[["O_soldier_TL_F",
		"O_soldier_UAV_F","O_UGV_01_rcws_F"],[[0,0,0],[5,-5,0],[-5,-5,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE"]]],0],
	// OI_ReconTeam_UAV
	[[[["O_soldier_TL_F",
		"O_soldier_UAV_F","O_UAV_02_F"],[[0,0,0],[5,-5,0],[-5,-5,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE"]]],0],
	// OI_AttackTeam_UAV
	[[[["O_soldier_TL_F",
		"O_soldier_UAV_F","O_UAV_02_CAS_F"],[[0,0,0],[5,-5,0],[-5,-5,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE"]]],0],
	// OI_ViperTeam
	[[[["O_V_Soldier_TL_hex_F",
		"O_V_Soldier_JTAC_hex_F","O_V_Soldier_M_hex_F",
		"O_V_Soldier_Exp_hex_F","O_V_Soldier_LAT_hex_F",
		"O_V_Soldier_Medic_hex_F"],[[0,0,0],[5,-5,0],[-5,-5,0],[10,-10,0],[-10,-10,0],[15,-15,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0]
];
