[
// configName "rhs_group_rus_msv_infantry_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_officer_armored","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_msv_infantry_squad",
[[[["rhs_msv_sergeant","rhs_msv_efreitor","rhs_msv_grenadier_rpg","rhs_msv_strelok_rpg_assist","rhs_msv_machinegunner","rhs_msv_LAT","rhs_msv_strelok_rpg_assist","rhs_msv_rifleman","rhs_msv_rifleman","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0],[17,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_squad_2mg",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_machinegunner","rhs_msv_rifleman","rhs_msv_machinegunner","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_squad_sniper",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_marksman","rhs_msv_rifleman","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_squad_mg_sniper",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_machinegunner","rhs_msv_rifleman","rhs_msv_marksman","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_section_mg",
[[[["rhs_msv_junior_sergeant","rhs_msv_machinegunner","rhs_msv_machinegunner_assistant","rhs_msv_grenadier","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],["LIEUTENANT","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_section_marksman",
[[[["rhs_msv_junior_sergeant","rhs_msv_machinegunner","rhs_msv_machinegunner_assistant","rhs_msv_grenadier","rhs_msv_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],["LIEUTENANT","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_section_AT",
[[[["rhs_msv_junior_sergeant","rhs_msv_at","rhs_msv_strelok_rpg_assist","rhs_msv_lat","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],["LIEUTENANT","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_section_AA",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_msv_aa","rhs_msv_aa","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],["LIEUTENANT","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_fireteam",
[[[["rhs_msv_sergeant","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_strelok_rpg_assist"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["LIEUTENANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_MANEUVER",
[[[["rhs_msv_efreitor","rhs_msv_rifleman","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0]],["LIEUTENANT","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_chq",
[[[["rhs_msv_emr_officer","rhs_msv_emr_officer_armored","rhs_msv_emr_officer_armored","rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_squad",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT","rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_squad_2mg",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_squad_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_squad_mg_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_section_mg",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_grenadier_rpg"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_section_marksman",
[[[["rhs_msv_emr_junior_sergeant","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_grenadier","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],["LIEUTENANT","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_section_AT",
[[[["rhs_msv_emr_junior_sergeant","rhs_msv_emr_at","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_lat","rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],["LIEUTENANT","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_section_AA",
[[[["rhs_msv_emr_junior_sergeant","rhs_msv_emr_aa","rhs_msv_emr_aa","rhs_msv_emr_aa","rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],["LIEUTENANT","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_fireteam",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_machinegunner","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","CORPORAL"]]],0.75],
// configName "rhs_group_rus_msv_infantry_emr_MANEUVER",
[[[["rhs_msv_emr_efreitor","rhs_msv_emr_LAT","rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0]],["CORPORAL","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_Ural_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_crew_commander","rhs_uaz_msv_01"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_msv_Ural_squad",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_grenadier","rhs_Ural_msv_01","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_strelok_rpg_assist","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_Ural_squad_2mg",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_machinegunner","rhs_Ural_msv_01","rhs_msv_machinegunner","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_Ural_squad_sniper",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_marksman","rhs_Ural_msv_01","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_Ural_squad_mg_sniper",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_machinegunner","rhs_Ural_msv_01","rhs_msv_marksman","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_Ural_squad_aa",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_msv_aa","rhs_Ural_Zu23_msv_01","rhs_vdv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_gaz66_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_crew_commander","rhs_uaz_msv_01"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_msv_gaz66_squad",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_grenadier","rhs_gaz66_msv","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_strelok_rpg_assist","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_gaz66_squad_2mg",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_machinegunner","rhs_gaz66_msv","rhs_msv_machinegunner","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_gaz66_squad_sniper",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_marksman","rhs_gaz66_msv","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_gaz66_squad_mg_sniper",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_machinegunner","rhs_gaz66_msv","rhs_msv_marksman","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_gaz66_squad_aa",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_gaz66_Zu23_msv"],[[0,5,0],[-5,0,0],[5,0,0]],["SERGEANT","CORPORAL","CORPORAL"]]],0.75],
// configName "rhs_group_rus_msv_btr70_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_crew_commander","rhs_btr70_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_msv_btr70_squad",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_grenadier","rhs_btr70_msv","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_strelok_rpg_assist","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_btr70_squad_2mg",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_machinegunner","rhs_btr70_msv","rhs_msv_machinegunner","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_btr70_squad_sniper",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_marksman","rhs_btr70_msv","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_btr70_squad_mg_sniper",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_machinegunner","rhs_btr70_msv","rhs_msv_marksman","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_btr70_squad_aa",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_msv_aa","rhs_btr70_msv","rhs_msv_machinegunner","rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_crew_commander","rhs_btr80_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_msv_BTR80_squad",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_btr80_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80_squad_2mg",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_btr80_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80_squad_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_btr80_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_marksman","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80_squad_mg_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_btr80_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80_squad_aa",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_msv_aa","rhs_btr80_msv","rhs_msv_machinegunner","rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80a_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_crew_commander","rhs_BTR80a_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_msv_BTR80a_squad",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_BTR80a_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80a_squad_2mg",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_BTR80a_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80a_squad_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_BTR80a_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_marksman","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80a_squad_mg_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_BTR80a_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_BTR80a_squad_aa",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_msv_aa","rhs_BTR80a_msv","rhs_msv_machinegunner","rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_bmp1_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_crew_commander","rhs_bmp1k_msv"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_msv_bmp1_squad",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_grenadier","rhs_bmp1p_msv","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_strelok_rpg_assist","rhs_msv_rifleman","rhs_msv_rifleman"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0],[37,-44,0],[-20,-20,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_bmp1_squad_2mg",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_machinegunner","rhs_bmp1p_msv","rhs_msv_machinegunner","rhs_msv_machinegunner_assistant","rhs_msv_LAT","rhs_msv_rifleman","rhs_msv_rifleman"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0],[37,-44,0],[-20,-20,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_bmp1_squad_sniper",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_marksman","rhs_bmp1p_msv","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_medic","rhs_msv_rifleman","rhs_msv_rifleman"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0],[37,-44,0],[-20,-20,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_bmp1_squad_mg_sniper",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_machinegunner","rhs_bmp1p_msv","rhs_msv_marksman","rhs_msv_machinegunner_assistant","rhs_msv_LAT","rhs_msv_rifleman","rhs_msv_rifleman"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0],[37,-44,0],[-20,-20,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_bmp1_squad_aa",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_msv_aa","rhs_bmp1p_msv","rhs_msv_machinegunner","rhs_msv_grenadier","rhs_msv_LAT"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_BMP3_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_crew_commander","rhs_bmp3_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_MSV_BMP3_squad",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_bmp3_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_BMP3_squad_2mg",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_bmp3_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_BMP3_squad_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_bmp3_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_marksman","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_BMP3_squad_mg_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_bmp3_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_BMP3_squad_aa",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_msv_aa","rhs_bmp3_msv","rhs_msv_machinegunner","rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_bmp3m_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_crew_commander","rhs_bmp3m_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_MSV_bmp3m_squad",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_bmp3m_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_bmp3m_squad_2mg",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_bmp3m_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_bmp3m_squad_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_bmp3m_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_marksman","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_bmp3m_squad_mg_sniper",
[[[["rhs_msv_emr_sergeant","rhs_msv_emr_efreitor","rhs_bmp3m_msv","rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_MSV_bmp3m_squad_aa",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_msv_aa","rhs_bmp3m_msv","rhs_msv_machinegunner","rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "RHS_SPGPlatoon_msv_bm21",
[[[["RHS_BM21_MSV_01","RHS_BM21_MSV_01","RHS_BM21_MSV_01","RHS_BM21_MSV_01","RHS_BM21_MSV_01","RHS_BM21_MSV_01"],[[0,0,0],[-20,-30,3],[20,-30,3],[40,-60,3],[60,-60,3],[80,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL","SERGEANT","CORPORAL"]]],0],
// configName "RHS_SPGSection_msv_bm21",
[[[["RHS_BM21_MSV_01","RHS_BM21_MSV_01"],[[0,0,0],[-20,-30,3]],["LIEUTENANT","SERGEANT"]]],0],
// configName "rhs_group_rus_msv_bmp2_chq",
[[[["rhs_msv_officer","rhs_msv_officer_armored","rhs_msv_crew_commander","rhs_bmp2k_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","LIEUTENANT","SERGEANT"]]],0.75],
// configName "rhs_group_rus_msv_bmp2_squad",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_grenadier","rhs_bmp2_msv","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_strelok_rpg_assist","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_bmp2_squad_2mg",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_machinegunner","rhs_bmp2_msv","rhs_msv_machinegunner","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_bmp2_squad_sniper",
[[[["rhs_msv_junior_sergeant","rhs_msv_efreitor","rhs_msv_marksman","rhs_bmp2_msv","rhs_msv_machinegunner","rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_bmp2_squad_mg_sniper",
[[[["rhs_msv_sergeant","rhs_msv_junior_sergeant","rhs_msv_machinegunner","rhs_bmp2_msv","rhs_msv_marksman","rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
// configName "rhs_group_rus_msv_bmp2_squad_aa",
[[[["rhs_msv_junior_sergeant","rhs_msv_aa","rhs_msv_aa","rhs_bmp2_msv","rhs_msv_machinegunner","rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75]]