
#include "..\include\ranks.sqf"

[_groups_map, east, "RHS_MSV", [[
	// configName "rhs_group_rus_msv_infantry_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_officer_armored",
		"rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_squad",
	[[[["rhs_msv_sergeant",
		"rhs_msv_efreitor","rhs_msv_grenadier_rpg",
		"rhs_msv_strelok_rpg_assist","rhs_msv_machinegunner",
		"rhs_msv_LAT","rhs_msv_strelok_rpg_assist",
		"rhs_msv_rifleman","rhs_msv_rifleman",
		"rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0],[17,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_squad_2mg",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_machinegunner",
		"rhs_msv_rifleman","rhs_msv_machinegunner",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_squad_sniper",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_marksman",
		"rhs_msv_rifleman","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_squad_mg_sniper",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_machinegunner",
		"rhs_msv_rifleman","rhs_msv_marksman",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_section_mg",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_machinegunner","rhs_msv_machinegunner_assistant",
		"rhs_msv_grenadier","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],
		["LIEUTENANT",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_section_marksman",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_machinegunner","rhs_msv_machinegunner_assistant",
		"rhs_msv_grenadier","rhs_msv_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],
		["LIEUTENANT",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_section_AT",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_at","rhs_msv_strelok_rpg_assist",
		"rhs_msv_lat","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],
		["LIEUTENANT",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_section_AA",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_msv_aa",
		"rhs_msv_aa","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],
		["LIEUTENANT",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_fireteam",
	[[[["rhs_msv_sergeant",
		"rhs_msv_machinegunner","rhs_msv_at",
		"rhs_msv_strelok_rpg_assist"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["LIEUTENANT",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_MANEUVER",
	[[[["rhs_msv_efreitor",
		"rhs_msv_rifleman","rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0]],
		["LIEUTENANT",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_chq",
	[[[["rhs_msv_emr_officer",
		"rhs_msv_emr_officer_armored","rhs_msv_emr_officer_armored",
		"rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_squad",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_msv_emr_grenadier_rpg",
		"rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner",
		"rhs_msv_emr_LAT","rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_squad_2mg",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_msv_emr_grenadier_rpg",
		"rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_squad_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_msv_emr_grenadier_rpg",
		"rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner",
		"rhs_msv_emr_LAT","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_squad_mg_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_msv_emr_grenadier_rpg",
		"rhs_msv_emr_strelok_rpg_assist","rhs_msv_emr_machinegunner",
		"rhs_msv_emr_machinegunner_assistant","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_section_mg",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant",
		"rhs_msv_emr_grenadier_rpg"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_section_marksman",
	[[[["rhs_msv_emr_junior_sergeant",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant",
		"rhs_msv_emr_grenadier","rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],
		["LIEUTENANT",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_section_AT",
	[[[["rhs_msv_emr_junior_sergeant",
		"rhs_msv_emr_at","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_lat","rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],
		["LIEUTENANT",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_section_AA",
	[[[["rhs_msv_emr_junior_sergeant",
		"rhs_msv_emr_aa","rhs_msv_emr_aa",
		"rhs_msv_emr_aa","rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],
		["LIEUTENANT",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_fireteam",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_grenadier_rpg",
		"rhs_msv_emr_strelok_rpg_assist"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT",
		"PRIVATE","PRIVATE",
		"CORPORAL"]]],0.75],
	// configName "rhs_group_rus_msv_infantry_emr_MANEUVER",
	[[[["rhs_msv_emr_efreitor",
		"rhs_msv_emr_LAT","rhs_msv_emr_rifleman"],[[0,5,0],[-5,0,0],[3,0,0]],
		["CORPORAL",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_Ural_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_crew_commander",
		"rhs_uaz_msv_01"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_msv_Ural_squad",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_grenadier",
		"rhs_Ural_msv_01","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_strelok_rpg_assist",
		"rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_Ural_squad_2mg",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_machinegunner",
		"rhs_Ural_msv_01","rhs_msv_machinegunner",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_Ural_squad_sniper",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_marksman",
		"rhs_Ural_msv_01","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_Ural_squad_mg_sniper",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_machinegunner",
		"rhs_Ural_msv_01","rhs_msv_marksman",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_Ural_squad_aa",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_msv_aa",
		"rhs_Ural_Zu23_msv_01","rhs_vdv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_gaz66_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_crew_commander",
		"rhs_uaz_msv_01"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_msv_gaz66_squad",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_grenadier",
		"rhs_gaz66_msv","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_strelok_rpg_assist",
		"rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_gaz66_squad_2mg",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_machinegunner",
		"rhs_gaz66_msv","rhs_msv_machinegunner",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_gaz66_squad_sniper",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_marksman",
		"rhs_gaz66_msv","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_gaz66_squad_mg_sniper",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_machinegunner",
		"rhs_gaz66_msv","rhs_msv_marksman",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_gaz66_squad_aa",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_gaz66_Zu23_msv"],[[0,5,0],[-5,0,0],[5,0,0]],
		["SERGEANT",
		"CORPORAL","CORPORAL"]]],0.75],
	// configName "rhs_group_rus_msv_btr70_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_crew_commander",
		"rhs_btr70_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_msv_btr70_squad",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_grenadier",
		"rhs_btr70_msv","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_strelok_rpg_assist",
		"rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_btr70_squad_2mg",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_machinegunner",
		"rhs_btr70_msv","rhs_msv_machinegunner",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_btr70_squad_sniper",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_marksman",
		"rhs_btr70_msv","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_btr70_squad_mg_sniper",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_machinegunner",
		"rhs_btr70_msv","rhs_msv_marksman",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_btr70_squad_aa",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_msv_aa",
		"rhs_btr70_msv","rhs_msv_machinegunner",
		"rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_crew_commander",
		"rhs_btr80_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80_squad",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_btr80_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80_squad_2mg",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_btr80_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner",
		"rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80_squad_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_btr80_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_marksman",
		"rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80_squad_mg_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_btr80_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant",
		"rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80_squad_aa",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_msv_aa",
		"rhs_btr80_msv","rhs_msv_machinegunner",
		"rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80a_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_crew_commander",
		"rhs_BTR80a_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80a_squad",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_BTR80a_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80a_squad_2mg",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_BTR80a_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner",
		"rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80a_squad_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_BTR80a_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_marksman",
		"rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80a_squad_mg_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_BTR80a_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant",
		"rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_BTR80a_squad_aa",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_msv_aa",
		"rhs_BTR80a_msv","rhs_msv_machinegunner",
		"rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_bmp1_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_crew_commander",
		"rhs_bmp1k_msv"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_msv_bmp1_squad",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_grenadier",
		"rhs_bmp1p_msv","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_strelok_rpg_assist",
		"rhs_msv_rifleman","rhs_msv_rifleman"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0],[37,-44,0],[-20,-20,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_bmp1_squad_2mg",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_machinegunner",
		"rhs_bmp1p_msv","rhs_msv_machinegunner",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT",
		"rhs_msv_rifleman","rhs_msv_rifleman"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0],[37,-44,0],[-20,-20,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_bmp1_squad_sniper",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_marksman",
		"rhs_bmp1p_msv","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_medic",
		"rhs_msv_rifleman","rhs_msv_rifleman"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0],[37,-44,0],[-20,-20,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_bmp1_squad_mg_sniper",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_machinegunner",
		"rhs_bmp1p_msv","rhs_msv_marksman",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT",
		"rhs_msv_rifleman","rhs_msv_rifleman"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0],[37,-44,0],[-20,-20,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_bmp1_squad_aa",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_msv_aa",
		"rhs_bmp1p_msv","rhs_msv_machinegunner",
		"rhs_msv_grenadier","rhs_msv_LAT"],[[0,0,0],[5,-5,0],[-5,-5,0],[19,-22,0],[-10,-11,0],[31,-39,0],[-15,-15,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_BMP3_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_crew_commander",
		"rhs_bmp3_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_MSV_BMP3_squad",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_bmp3_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_BMP3_squad_2mg",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_bmp3_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner",
		"rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_BMP3_squad_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_bmp3_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_marksman",
		"rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_BMP3_squad_mg_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_bmp3_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant",
		"rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_BMP3_squad_aa",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_msv_aa",
		"rhs_bmp3_msv","rhs_msv_machinegunner",
		"rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_bmp3m_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_crew_commander",
		"rhs_bmp3m_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_MSV_bmp3m_squad",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_bmp3m_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_bmp3m_squad_2mg",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_bmp3m_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner",
		"rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_bmp3m_squad_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_bmp3m_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_marksman",
		"rhs_msv_emr_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_bmp3m_squad_mg_sniper",
	[[[["rhs_msv_emr_sergeant",
		"rhs_msv_emr_efreitor","rhs_bmp3m_msv",
		"rhs_msv_emr_grenadier_rpg","rhs_msv_emr_strelok_rpg_assist",
		"rhs_msv_emr_machinegunner","rhs_msv_emr_machinegunner_assistant",
		"rhs_msv_emr_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_MSV_bmp3m_squad_aa",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_msv_aa",
		"rhs_bmp3m_msv","rhs_msv_machinegunner",
		"rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "RHS_SPGPlatoon_msv_bm21",
	[[[["RHS_BM21_MSV_01",
		"RHS_BM21_MSV_01","RHS_BM21_MSV_01",
		"RHS_BM21_MSV_01","RHS_BM21_MSV_01",
		"RHS_BM21_MSV_01"],[[0,0,0],[-20,-30,3],[20,-30,3],[40,-60,3],[60,-60,3],[80,-60,3]],
		["LIEUTENANT",
		"SERGEANT","SERGEANT",
		"CORPORAL","SERGEANT",
		"CORPORAL"]]],0],
	// configName "RHS_SPGSection_msv_bm21",
	[[[["RHS_BM21_MSV_01","RHS_BM21_MSV_01"],[[0,0,0],[-20,-30,3]],
		["LIEUTENANT","SERGEANT"]]],0],
	// configName "rhs_group_rus_msv_bmp2_chq",
	[[[["rhs_msv_officer",
		"rhs_msv_officer_armored","rhs_msv_crew_commander",
		"rhs_bmp2k_msv"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["CAPTAIN",
		"LIEUTENANT","LIEUTENANT",
		"SERGEANT"]]],0.75],
	// configName "rhs_group_rus_msv_bmp2_squad",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_grenadier",
		"rhs_bmp2_msv","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_strelok_rpg_assist",
		"rhs_msv_rifleman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_bmp2_squad_2mg",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_machinegunner",
		"rhs_bmp2_msv","rhs_msv_machinegunner",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_bmp2_squad_sniper",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_efreitor","rhs_msv_marksman",
		"rhs_bmp2_msv","rhs_msv_machinegunner",
		"rhs_msv_at","rhs_msv_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_bmp2_squad_mg_sniper",
	[[[["rhs_msv_sergeant",
		"rhs_msv_junior_sergeant","rhs_msv_machinegunner",
		"rhs_bmp2_msv","rhs_msv_marksman",
		"rhs_msv_machinegunner_assistant","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_rus_msv_bmp2_squad_aa",
	[[[["rhs_msv_junior_sergeant",
		"rhs_msv_aa","rhs_msv_aa",
		"rhs_bmp2_msv","rhs_msv_machinegunner",
		"rhs_msv_grenadier","rhs_msv_LAT"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE"]]],0.75]
], _copyRef] call gosa_fnc_filtering_squads_byAvail_v2,
[1990,2100], [160,999],
["CUP_O_RU","OPF_SFIA_lxWS","OPF_TURA_lxWS","OPF_T_F","OPF_F","OPF_G_F","OPF_R_F"]
] call gosa_fnc_map_groups_add;

	[_groups_map, east, "RHS_TV", [[
		// configName "RHS_T14Platoon",
		[[[["RHS_T14_tv","RHS_T14_tv","RHS_T14_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T14Platoon_AA",
		[[[["RHS_T14_tv","rhs_zsu234_aa","RHS_T14_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T14Section",
		[[[["RHS_T14_tv","RHS_T14_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BAPlatoon",
		[[[["rhs_t72ba_tv","rhs_t72ba_tv","rhs_t72ba_tv"],[[0,0,0],[20,-30,3],[-21,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BAPlatoon_AA",
		[[[["rhs_t72ba_tv","rhs_zsu234_aa","rhs_t72ba_tv","rhs_zsu234_aa"],[[0,0,0],[20,-30,3],[-21,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_T72BASection",
		[[[["rhs_t72ba_tv","rhs_t72ba_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BBPlatoon",
		[[[["RHS_T72BB_tv","RHS_T72BB_tv","RHS_T72BB_tv"],[[0,0,0],[20,-30,3],[-21,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BBPlatoon_AA",
		[[[["RHS_T72BB_tv","rhs_zsu234_aa","RHS_T72BB_tv"],[[0,0,0],[20,-30,3],[-21,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BBSection",
		[[[["RHS_T72BB_tv","RHS_T72BB_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BCPlatoon",
		[[[["RHS_T72BC_tv","RHS_T72BC_tv","RHS_T72BC_tv"],[[0,0,0],[20,-30,3],[-21,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BCPlatoon_AA",
		[[[["RHS_T72BC_tv","rhs_zsu234_aa","RHS_T72BC_tv","rhs_zsu234_aa"],[[0,0,0],[20,-30,3],[-21,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_T72BCSection",
		[[[["RHS_T72BC_tv","RHS_T72BC_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BDPlatoon",
		[[[["RHS_T72BD_tv","RHS_T72BD_tv","RHS_T72BD_tv"],[[0,0,0],[20,-30,3],[-21,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BDPlatoon_AA",
		[[[["RHS_T72BD_tv","rhs_zsu234_aa","RHS_T72BD_tv","rhs_zsu234_aa"],[[0,0,0],[20,-30,3],[-21,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_T72BDSection",
		[[[["RHS_T72BD_tv","RHS_T72BD_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BEPlatoon",
		[[[["rhs_t72be_tv","rhs_t72be_tv","rhs_t72be_tv"],[[0,0,0],[20,-30,3],[-21,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T72BEPlatoon_AA",
		[[[["rhs_t72be_tv","rhs_zsu234_aa","rhs_t72be_tv","rhs_zsu234_aa"],[[0,0,0],[20,-30,3],[-21,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_T72BESection",
		[[[["rhs_t72be_tv","rhs_t72be_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T80Platoon",
		[[[["RHS_T80","RHS_T80","RHS_T80"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T80Platoon_AA",
		[[[["RHS_T80","rhs_zsu234_aa","RHS_T80"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T80Section",
		[[[["RHS_T80","RHS_T80"],[[0,0,0],[-20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T80BPlatoon",
		[[[["RHS_T80B","RHS_T80B","RHS_T80B"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T80BPlatoon_AA",
		[[[["RHS_T80B","rhs_zsu234_aa","RHS_T80B","rhs_zsu234_aa"],[[0,0,0],[20.1,-30,3],[-20,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_T80BSection",
		[[[["RHS_T80B","RHS_T80B"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T80BVPlatoon",
		[[[["RHS_T80BV","RHS_T80BV","RHS_T80BV"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T80BVPlatoon_AA",
		[[[["RHS_T80BV","rhs_zsu234_aa","RHS_T80BV","rhs_zsu234_aa"],[[0,0,0],[20.1,-30,3],[-20,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_T80BVSection",
		[[[["RHS_T80BV","RHS_T80BV"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T80APlatoon",
		[[[["RHS_T80A","RHS_T80A","RHS_T80A"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T80APlatoon_AA",
		[[[["RHS_T80A","rhs_zsu234_aa","RHS_T80A","rhs_zsu234_aa"],[[0,0,0],[20.1,-30,3],[-20,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_T80ASection",
		[[[["RHS_T80A","RHS_T80A"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T80UPlatoon",
		[[[["RHS_T80U","RHS_T80U","RHS_T80U"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T80UPlatoon_AA",
		[[[["RHS_T80U","rhs_zsu234_aa","RHS_T80U","rhs_zsu234_aa"],[[0,0,0],[20.1,-30,3],[-20,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_T80USection",
		[[[["RHS_T80U","RHS_T80U"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T80UMPlatoon",
		[[[["RHS_T80UM","RHS_T80UM","RHS_T80UM"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T80UMPlatoon_AA",
		[[[["RHS_T80UM","rhs_zsu234_aa","RHS_T80UM","rhs_zsu234_aa"],[[0,0,0],[20.1,-30,3],[-20,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_T80UMSection",
		[[[["RHS_T80UM","RHS_T80UM"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "rhs_t80ue1Platoon",
		[[[["rhs_t80ue1","rhs_t80ue1","rhs_t80ue1"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "rhs_t80ue1Platoon_AA",
		[[[["rhs_t80ue1","rhs_zsu234_aa","rhs_t80ue1","rhs_zsu234_aa"],[[0,0,0],[20.1,-30,3],[-20,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "rhs_t80ue1Section",
		[[[["rhs_t80ue1","rhs_t80ue1"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "rhs_t80u45mPlatoon",
		[[[["rhs_t80u45m","rhs_t80u45m","rhs_t80u45m"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "rhs_t80u45mPlatoon_AA",
		[[[["rhs_t80u45m","rhs_zsu234_aa","rhs_t80u45m","rhs_zsu234_aa"],[[0,0,0],[20.1,-30,3],[-20,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "rhs_t80u45mSection",
		[[[["rhs_t80u45m","rhs_t80u45m"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T90Platoon",
		[[[["RHS_T90_tv","RHS_T90_tv","RHS_T90_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90Platoon_AA",
		[[[["RHS_T90_tv","rhs_zsu234_aa","RHS_T90_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90Section",
		[[[["RHS_T90_tv","RHS_T90_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_t90aPlatoon",
		[[[["RHS_t90a_tv","RHS_t90a_tv","RHS_t90a_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_t90aPlatoon_AA",
		[[[["RHS_t90a_tv","rhs_zsu234_aa","RHS_t90a_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_t90aSection",
		[[[["RHS_t90a_tv","RHS_t90a_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T90AMPlatoon",
		[[[["RHS_T90AM_tv","RHS_T90AM_tv","RHS_T90AM_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90AMPlatoon_AA",
		[[[["RHS_T90AM_tv","rhs_zsu234_aa","RHS_T90AM_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90AMSection",
		[[[["RHS_T90AM_tv","RHS_T90AM_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T90SMPlatoon",
		[[[["RHS_T90SM_tv","RHS_T90SM_tv","RHS_T90SM_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90SMPlatoon_AA",
		[[[["RHS_T90SM_tv","rhs_zsu234_aa","RHS_T90SM_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90SMSection",
		[[[["RHS_T90SM_tv","RHS_T90SM_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T90SAPlatoon",
		[[[["rhs_t90saa_tv","rhs_t90saa_tv","rhs_t90saa_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90SAPlatoon_AA",
		[[[["rhs_t90saa_tv","rhs_zsu234_aa","rhs_t90saa_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90SASection",
		[[[["rhs_t90saa_tv","rhs_t90saa_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_T90SABPlatoon",
		[[[["rhs_t90sab_tv","rhs_t90sab_tv","rhs_t90sab_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90SABPlatoon_AA",
		[[[["rhs_t90sab_tv","rhs_zsu234_aa","rhs_t90sab_tv"],[[0,0,0],[20.1,-30,3],[-20,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.025],
		// configName "RHS_T90SABSection",
		[[[["rhs_t90sab_tv","rhs_t90sab_tv"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.025]
	], _copyRef] call gosa_fnc_filtering_squads_byAvail_v2,
	[1990,2100], [160,999],
	["CUP_O_RU","OPF_SFIA_lxWS","OPF_TURA_lxWS","OPF_T_F","OPF_F","OPF_G_F"]
	] call gosa_fnc_map_groups_add;
	// Arty
	/*
	_east=_east+[
		// configName "RHS_SPGPlatoon_tv_2S1",
		[[[["rhs_2S1_tv","rhs_2S1_tv","rhs_2S1_tv","rhs_2S1_tv"],[[0,0,0],[20,-30,3],[-20.1,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_SPGSection_tv_2S1",
		[[[["rhs_2S1_tv","rhs_2S1_tv"],[[0,0,0],[20,-30,3]],["LIEUTENANT","SERGEANT"]]],0.025],
		// configName "RHS_SPGPlatoon_tv_2s3",
		[[[["rhs_2s3_tv","rhs_2s3_tv","rhs_2s3_tv","rhs_2s3_tv"],[[0,0,0],[20,-30,3],[-20.1,-30,3],[40,-60,3]],["LIEUTENANT","SERGEANT","SERGEANT","CORPORAL"]]],0.025],
		// configName "RHS_SPGSection_tv_2s3",
		[[[["rhs_2s3_tv","rhs_2s3_tv"],[[0,0,0],[20,-30,3]],["LIEUTENANT","SERGEANT"]]],0.025]
	];
	*/


// nato_usmc_wd
[_groups_map, west, "RHS_USMC_WD", [[
	// configName "rhs_group_nato_usmc_wd_infantry_squad",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman",
		"rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_rifleman_m4",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman",
		"rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_riflemanat",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman",
		"rhsusf_usmc_marpat_wd_rifleman_m4","rhsusf_usmc_marpat_wd_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0],[17,0,0],[19,0,0],[21,0,0],[23,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE","CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_infantry_weaponsquad",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner",
		"rhsusf_usmc_marpat_wd_machinegunner_ass","rhsusf_usmc_marpat_wd_teamleader",
		"rhsusf_usmc_marpat_wd_machinegunner","rhsusf_usmc_marpat_wd_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","CORPORAL",
		"PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_infantry_squad_sniper",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter",
		"rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter",
		"rhsusf_usmc_marpat_wd_sniper","rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_infantry_team",
	[[[["rhsusf_usmc_marpat_wd_teamleader",
		"rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4",
		"rhsusf_usmc_marpat_wd_riflemanat"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_infantry_team_MG",
	[[[["rhsusf_usmc_marpat_wd_teamleader",
		"rhsusf_usmc_marpat_wd_machinegunner","rhsusf_usmc_marpat_wd_machinegunner_ass",
		"rhsusf_usmc_marpat_wd_rifleman_m4"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_infantry_team_AA",
	[[[["rhsusf_usmc_marpat_wd_teamleader",
		"rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4",
		"rhsusf_usmc_marpat_wd_stinger"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT",
		"PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_infantry_team_support",
	[[[["rhsusf_usmc_marpat_wd_teamleader",
		"rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4",
		"rhsusf_navy_marpat_wd_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT",
		"PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_infantry_team_heavy_AT",
	[[[["rhsusf_usmc_marpat_wd_teamleader",
		"rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_rifleman_m4",
		"rhsusf_usmc_marpat_wd_javelin"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT",
		"PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_wd_infantry_team",
	[[[["rhsusf_usmc_recon_marpat_wd_teamleader",
		"rhsusf_usmc_recon_marpat_wd_marksman","rhsusf_usmc_recon_marpat_wd_autorifleman",
		"rhsusf_usmc_recon_marpat_wd_rifleman_at","rhsusf_usmc_recon_marpat_wd_rifleman",
		"rhsusf_usmc_recon_marpat_wd_machinegunner_m249"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL",
		"CORPORAL","CORPORAL",
		"CORPORAL"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_wd_infantry_team_MG",
	[[[["rhsusf_usmc_recon_marpat_wd_teamleader",
		"rhsusf_usmc_recon_marpat_wd_marksman","rhsusf_usmc_recon_marpat_wd_autorifleman",
		"rhsusf_usmc_recon_marpat_wd_rifleman_at","rhsusf_usmc_recon_marpat_wd_rifleman",
		"rhsusf_usmc_recon_marpat_wd_machinegunner"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_wd_infantry_team_support",
	[[[["rhsusf_usmc_recon_marpat_wd_teamleader",
		"rhsusf_usmc_recon_marpat_wd_marksman","rhsusf_usmc_recon_marpat_wd_autorifleman",
		"rhsusf_navy_sarc_w","rhsusf_usmc_recon_marpat_wd_rifleman",
		"rhsusf_usmc_recon_marpat_wd_machinegunner_m249"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_wd_infantry_team_lite",
	[[[["rhsusf_usmc_recon_marpat_wd_teamleader_lite",
		"rhsusf_usmc_recon_marpat_wd_marksman_lite","rhsusf_usmc_recon_marpat_wd_autorifleman_lite",
		"rhsusf_usmc_recon_marpat_wd_rifleman_at_lite","rhsusf_usmc_recon_marpat_wd_rifleman_lite",
		"rhsusf_usmc_recon_marpat_wd_machinegunner_m249_lite"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL",
		"CORPORAL","CORPORAL","CORPORAL"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_wd_infantry_team_fast",
	[[[["rhsusf_usmc_recon_marpat_wd_teamleader_fast",
		"rhsusf_usmc_recon_marpat_wd_marksman_fast","rhsusf_usmc_recon_marpat_wd_autorifleman_fast",
		"rhsusf_usmc_recon_marpat_wd_rifleman_at_fast","rhsusf_usmc_recon_marpat_wd_rifleman_fast",
		"rhsusf_usmc_recon_marpat_wd_machinegunner_m249_fast"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
	// configName "BUS_MotInf_Team_GMG",
	[[[["rhsusf_m1025_w_s_Mk19",
		"rhsusf_usmc_marpat_wd_autorifleman","rhsusf_usmc_marpat_wd_riflemanat",
		"rhsusf_usmc_marpat_wd_rifleman"],[[0,0,0],[-12,-12,0],[14,-13,0],[5,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL"]]],0],
	// configName "BUS_MotInf_Team_HMG",
	[[[["rhsusf_m1025_w_s_m2",
		"rhsusf_usmc_marpat_wd_rifleman","rhsusf_usmc_marpat_wd_riflemanat",
		"rhsusf_usmc_marpat_wd_rifleman"],[[0,0,0],[-12,-12,0],[14,-13,0],[5,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL"]]],0],
	// configName "BUS_MotInf_AT",
	[[[["rhsusf_m1025_w_s",
		"rhsusf_usmc_marpat_wd_rifleman","rhsusf_usmc_marpat_wd_javelin",
		"rhsusf_usmc_marpat_wd_javelin"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],
		["SERGEANT",
		"CORPORAL","CORPORAL",
		"PRIVATE"]]],0],
	// configName "BUS_MotInf_AA",
	[[[["rhsusf_m1025_w_s",
		"rhsusf_usmc_marpat_wd_rifleman","rhsusf_usmc_marpat_wd_stinger",
		"rhsusf_usmc_marpat_wd_stinger"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],
		["SERGEANT",
		"CORPORAL","CORPORAL",
		"PRIVATE"]]],0],
	// configName "rhs_group_nato_usmc_wd_RG33_squad",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman",
		"rhsusf_rg33_usmc_wd","rhsusf_usmc_marpat_wd_autorifleman",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_riflemanat",
		"rhsusf_usmc_marpat_wd_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_RG33_squad_2mg",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner",
		"rhsusf_rg33_usmc_wd","rhsusf_usmc_marpat_wd_machinegunner_ass",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner",
		"rhsusf_usmc_marpat_wd_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_RG33_squad_sniper",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper",
		"rhsusf_rg33_usmc_wd","rhsusf_usmc_marpat_wd_spotter",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper",
		"rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_RG33_squad_mg_sniper",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_army_ocp_teamleader","rhsusf_usmc_marpat_wd_machinegunner",
		"rhsusf_rg33_usmc_wd","rhsusf_usmc_marpat_wd_machinegunner_ass",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper",
		"rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_RG33_m2_squad",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman",
		"rhsusf_rg33_m2_usmc_wd","rhsusf_usmc_marpat_wd_autorifleman",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_riflemanat",
		"rhsusf_usmc_marpat_wd_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_RG33_m2_squad_2mg",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner",
		"rhsusf_rg33_m2_usmc_wd","rhsusf_usmc_marpat_wd_machinegunner_ass",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner",
		"rhsusf_usmc_marpat_wd_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_RG33_m2_squad_sniper",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_autorifleman",
		"rhsusf_rg33_m2_usmc_wd","rhsusf_usmc_marpat_wd_spotter",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper",
		"rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_wd_RG33_m2_squad_mg_sniper",
	[[[["rhsusf_usmc_marpat_wd_squadleader",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_machinegunner",
		"rhsusf_rg33_m2_usmc_wd","rhsusf_usmc_marpat_wd_machinegunner_ass",
		"rhsusf_usmc_marpat_wd_teamleader","rhsusf_usmc_marpat_wd_sniper",
		"rhsusf_usmc_marpat_wd_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "RHS_M1A1AIM_wd_Platoon",
	[[[["rhsusf_m1a1fep_wd",
		"rhsusf_m1a1fep_wd","rhsusf_m1a1fep_wd",
		"rhsusf_m1a1fep_wd"],[[0,0,0],[-20,-30,3],[20,-30,3],[40,-60,3]],
		["LIEUTENANT",
		"SERGEANT","SERGEANT","CORPORAL"]]],0],
	// configName "RHS_M1A1FEP_wd_Section",
	[[[["rhsusf_m1a1fep_wd","rhsusf_m1a1fep_wd"],[[0,0,0],[-20,-30,2]],
		["LIEUTENANT","SERGEANT"]]],0]
], _copyRef] call gosa_fnc_filtering_squads_byAvail_v2,
[1990,2100], [160,249],
["CUP_B_US_Army","CUP_B_USMC","BLU_G_F","BLU_F","BLU_T_F","BLU_NATO_lxWS","BLU_TURA_lxWS","BLU_W_F"]
] call gosa_fnc_map_groups_add;

// nato_usmc_d
[_groups_map, west, "RHS_USMC_D", [[
	// configName "rhs_group_nato_usmc_d_infantry_squad",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman",
		"rhsusf_usmc_marpat_d_rifleman","rhsusf_usmc_marpat_d_rifleman_m4",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman",
		"rhsusf_usmc_marpat_d_rifleman_m4","rhsusf_usmc_marpat_d_riflemanat",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman",
		"rhsusf_usmc_marpat_d_rifleman_m4","rhsusf_usmc_marpat_d_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0],[17,0,0],[19,0,0],[21,0,0],[23,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"PRIVATE","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_infantry_weaponsquad",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner",
		"rhsusf_usmc_marpat_d_machinegunner_ass","rhsusf_usmc_marpat_d_teamleader",
		"rhsusf_usmc_marpat_d_machinegunner","rhsusf_usmc_marpat_d_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","CORPORAL","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_infantry_squad_sniper",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter",
		"rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter",
		"rhsusf_usmc_marpat_d_sniper","rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[9,0,0],[11,0,0],[13,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE",
		"CORPORAL","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_infantry_team",
	[[[["rhsusf_usmc_marpat_d_teamleader",
		"rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4",
		"rhsusf_usmc_marpat_d_riflemanat"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_infantry_team_MG",
	[[[["rhsusf_usmc_marpat_d_teamleader",
		"rhsusf_usmc_marpat_d_machinegunner","rhsusf_usmc_marpat_d_machinegunner_ass",
		"rhsusf_usmc_marpat_d_rifleman_m4"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_infantry_team_AA",
	[[[["rhsusf_usmc_marpat_d_teamleader",
		"rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4",
		"rhsusf_usmc_marpat_d_stinger"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_infantry_team_support",
	[[[["rhsusf_usmc_marpat_d_teamleader",
		"rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4",
		"rhsusf_navy_marpat_d_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_infantry_team_heavy_AT",
	[[[["rhsusf_usmc_marpat_d_teamleader",
		"rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_rifleman_m4",
		"rhsusf_usmc_marpat_d_javelin"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],
		["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_d_infantry_team",
	[[[["rhsusf_usmc_recon_marpat_d_teamleader",
		"rhsusf_usmc_recon_marpat_d_marksman","rhsusf_usmc_recon_marpat_d_autorifleman",
		"rhsusf_usmc_recon_marpat_d_rifleman_at","rhsusf_usmc_recon_marpat_d_rifleman",
		"rhsusf_usmc_recon_marpat_d_machinegunner_m249"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_d_infantry_team_MG",
	[[[["rhsusf_usmc_recon_marpat_d_teamleader",
		"rhsusf_usmc_recon_marpat_d_marksman","rhsusf_usmc_recon_marpat_d_autorifleman",
		"rhsusf_usmc_recon_marpat_d_rifleman_at","rhsusf_usmc_recon_marpat_d_rifleman",
		"rhsusf_usmc_recon_marpat_d_machinegunner"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_d_infantry_team_support",
	[[[["rhsusf_usmc_recon_marpat_d_teamleader",
		"rhsusf_usmc_recon_marpat_d_marksman","rhsusf_usmc_recon_marpat_d_autorifleman",
		"rhsusf_navy_sarc_d","rhsusf_usmc_recon_marpat_d_rifleman",
		"rhsusf_usmc_recon_marpat_d_machinegunner_m249"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_d_infantry_team_lite",
	[[[["rhsusf_usmc_recon_marpat_d_teamleader_lite",
		"rhsusf_usmc_recon_marpat_d_marksman_lite","rhsusf_usmc_recon_marpat_d_autorifleman_lite",
		"rhsusf_usmc_recon_marpat_d_rifleman_at_lite","rhsusf_usmc_recon_marpat_d_rifleman_lite",
		"rhsusf_usmc_recon_marpat_d_machinegunner_m249_lite"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
	// configName "rhs_group_nato_usmc_recon_d_infantry_team_fast",
	[[[["rhsusf_usmc_recon_marpat_d_teamleader_fast",
		"rhsusf_usmc_recon_marpat_d_marksman_fast","rhsusf_usmc_recon_marpat_d_autorifleman_fast",
		"rhsusf_usmc_recon_marpat_d_rifleman_at_fast","rhsusf_usmc_recon_marpat_d_rifleman_fast",
		"rhsusf_usmc_recon_marpat_d_machinegunner_m249_fast"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],
		["SERGEANT",
		"SERGEANT","CORPORAL","CORPORAL","CORPORAL","CORPORAL"]]],0.75],
	// configName "rhs_group_nato_usmc_d_RG33_squad",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman",
		"rhsusf_rg33_usmc_d","rhsusf_usmc_marpat_d_autorifleman",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_riflemanat",
		"rhsusf_usmc_marpat_d_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_RG33_squad_2mg",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner",
		"rhsusf_rg33_usmc_d","rhsusf_usmc_marpat_d_machinegunner_ass",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner",
		"rhsusf_usmc_marpat_d_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_RG33_squad_sniper",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper",
		"rhsusf_rg33_usmc_d","rhsusf_usmc_marpat_d_spotter",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper",
		"rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_RG33_squad_mg_sniper",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_army_ocp_teamleader","rhsusf_usmc_marpat_d_machinegunner",
		"rhsusf_rg33_usmc_d","rhsusf_usmc_marpat_d_machinegunner_ass",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper",
		"rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_RG33_m2_squad",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman",
		"rhsusf_rg33_m2_usmc_d","rhsusf_usmc_marpat_d_autorifleman",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_riflemanat",
		"rhsusf_usmc_marpat_d_marksman"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_RG33_m2_squad_2mg",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner",
		"rhsusf_rg33_m2_usmc_d","rhsusf_usmc_marpat_d_machinegunner_ass",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner",
		"rhsusf_usmc_marpat_d_machinegunner_ass"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_RG33_m2_squad_sniper",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_autorifleman",
		"rhsusf_rg33_m2_usmc_d","rhsusf_usmc_marpat_d_spotter",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper",
		"rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "rhs_group_nato_usmc_d_RG33_m2_squad_mg_sniper",
	[[[["rhsusf_usmc_marpat_d_squadleader",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_machinegunner",
		"rhsusf_rg33_m2_usmc_d","rhsusf_usmc_marpat_d_machinegunner_ass",
		"rhsusf_usmc_marpat_d_teamleader","rhsusf_usmc_marpat_d_sniper",
		"rhsusf_usmc_marpat_d_spotter"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[15,0,0]],
		["SERGEANT",
		"SERGEANT","PRIVATE",
		"CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]],0.75],
	// configName "BUS_MotInf_Team_GMG",
	[[[["rhsusf_m1025_d_s_Mk19",
	"rhsusf_usmc_marpat_d_autorifleman","rhsusf_usmc_marpat_d_riflemanat",
	"rhsusf_usmc_marpat_d_rifleman"],[[0,0,0],[-12,-12,0],[14,-13,0],[5,0,0]],
	["SERGEANT",
	"CORPORAL","PRIVATE","CORPORAL"]]],0],
	// configName "BUS_MotInf_Team_HMG",
	[[[["rhsusf_m1025_d_s_m2",
		"rhsusf_usmc_marpat_d_rifleman","rhsusf_usmc_marpat_d_riflemanat",
		"rhsusf_usmc_marpat_d_rifleman"],[[0,0,0],[-12,-12,0],[14,-13,0],[5,0,0]],
		["SERGEANT",
		"CORPORAL","PRIVATE","CORPORAL"]]],0],
	// configName "BUS_MotInf_AT",
	[[[["rhsusf_m1025_d_s",
		"rhsusf_usmc_marpat_d_rifleman","rhsusf_usmc_marpat_d_javelin",
		"rhsusf_usmc_marpat_d_javelin"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],
		["SERGEANT",
		"CORPORAL","CORPORAL","PRIVATE"]]],0],
	// configName "BUS_MotInf_AA",
	[[[["rhsusf_m1025_d_s",
		"rhsusf_usmc_marpat_d_rifleman","rhsusf_usmc_marpat_d_stinger",
		"rhsusf_usmc_marpat_d_stinger"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],
		["SERGEANT",
		"CORPORAL","CORPORAL","PRIVATE"]]],0],
	// configName "RHS_M1A1AIM_d_Platoon",
	[[[["rhsusf_m1a1fep_d",
		"rhsusf_m1a1fep_d","rhsusf_m1a1fep_d",
		"rhsusf_m1a1fep_d"],[[0,0,0],[-20,-30,3],[20,-30,3],[40,-60,3]],
		["LIEUTENANT",
		"SERGEANT","SERGEANT","CORPORAL"]]],0],
	// configName "RHS_M1A1FEP_d_Section",
	[[[["rhsusf_m1a1fep_d","rhsusf_m1a1fep_d"],[[0,0,0],[-20,-30,2]],
		["LIEUTENANT","SERGEANT"]]],0]
], _copyRef] call gosa_fnc_filtering_squads_byAvail_v2,
[1990,2100], [250,999],
["CUP_B_US_Army","CUP_B_USMC","BLU_G_F","BLU_F","BLU_T_F","BLU_NATO_lxWS","BLU_TURA_lxWS","BLU_W_F"]
] call gosa_fnc_map_groups_add;


//--- Indep
_arr = [
	// rhssaf_group_army_m93_oakleaf_company_hq
	[[[["rhssaf_army_m93_oakleaf_summer_officer","rhssaf_army_m93_oakleaf_summer_officer","rhssaf_army_m93_oakleaf_summer_sq_lead","rhssaf_army_m93_oakleaf_summer_rifleman_m70"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","SERGEANT","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m93_oakleaf_platoon_hq
	[[[["rhssaf_army_m93_oakleaf_summer_officer","rhssaf_army_m93_oakleaf_summer_sq_lead","rhssaf_army_m93_oakleaf_summer_medic","rhssaf_army_m93_oakleaf_summer_sq_lead","rhssaf_army_m93_oakleaf_summer_rifleman_m70","rhssaf_army_m93_oakleaf_summer_rifleman_m70"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["LIEUTENANT","SERGEANT","SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m93_oakleaf_infantry_squad
	[[[["rhssaf_army_m93_oakleaf_summer_sq_lead","rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_rifleman_m70","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]
	],0.75],
	// rhssaf_group_army_m93_oakleaf_infantry_weaponsquad
	[[[["rhssaf_army_m93_oakleaf_summer_sq_lead","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_asst_mgun","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE"]]
	],0.3],
	// rhssaf_group_army_m93_oakleaf_infantry_squad_sniper
	[[[["rhssaf_army_m93_oakleaf_summer_sq_lead","rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_sniper_m76","rhssaf_army_m93_oakleaf_summer_asst_mgun","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]
	],0.3],
	// rhssaf_group_army_m93_oakleaf_infantry_team
	[[[["rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]
	],0.2],
	// rhssaf_group_army_m93_oakleaf_infantry_team_mg
	[[[["rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_asst_mgun"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.2],
	// rhssaf_group_army_m93_oakleaf_infantry_team_AA
	[[[["rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_spec_aa"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m93_oakleaf_infantry_team_support
	[[[["rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.2],
	// rhssaf_group_army_m93_oakleaf_infantry_team_heavy_at
	[[[["rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_spec_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]
	],0.4],
	// rhssaf_group_army_ural_squad
	[[[["rhssaf_army_m93_oakleaf_summer_sq_lead","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_m93_oakleaf_summer_gl","rhssaf_army_ural","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_rifleman_at","rhssaf_army_m93_oakleaf_summer_rifleman_m70","rhssaf_army_m93_oakleaf_summer_sniper_m76"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_ural_squad_mg
	[[[["rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_rifleman_m70","rhssaf_army_m93_oakleaf_summer_rifleman_m70","rhssaf_army_ural_open","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_rifleman_at","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_mgun_m84"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]
	],0.2],
	// rhssaf_group_army_ural_squad_sniper
	[[[["rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_rifleman_m70","rhssaf_army_m93_oakleaf_summer_sniper_m76","rhssaf_army_ural","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_rifleman_at","rhssaf_army_m93_oakleaf_summer_medic","rhssaf_army_m93_oakleaf_summer_rifleman_m21","rhssaf_army_m93_oakleaf_summer_rifleman_m21"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_ural_squad_mg_sniper
	[[[["rhssaf_army_m93_oakleaf_summer_sq_lead","rhssaf_army_m93_oakleaf_summer_ft_lead","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_ural","rhssaf_army_m93_oakleaf_summer_sniper_m76","rhssaf_army_m93_oakleaf_summer_mgun_m84","rhssaf_army_m93_oakleaf_summer_rifleman_at","rhssaf_army_m93_oakleaf_summer_rifleman_m70","rhssaf_army_m93_oakleaf_summer_rifleman_m70"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","SERGEANT","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE","PRIVATE","PRIVATE"]]
	],0.1]
];
_arr append [
	// rhssaf_group_army_m10_digital_company_hq
	[[[["rhssaf_army_m10_digital_officer","rhssaf_army_m10_digital_officer","rhssaf_army_m10_digital_sq_lead","rhssaf_army_m10_digital_rifleman_m21"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","SERGEANT","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m10_digital_platoon_hq
	[[[["rhssaf_army_m10_digital_officer","rhssaf_army_m10_digital_sq_lead","rhssaf_army_m10_digital_medic","rhssaf_army_m10_digital_sq_lead","rhssaf_army_m10_digital_rifleman_m21","rhssaf_army_m10_digital_rifleman_m70"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["LIEUTENANT","SERGEANT","SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m10_digital_infantry_squad
	[[[["rhssaf_army_m10_digital_sq_lead","rhssaf_army_m10_digital_ft_lead","rhssaf_army_m10_digital_rifleman_m21","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_ft_lead","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]],0.9],
	// rhssaf_group_army_m10_digital_infantry_weaponsquad
	[[[["rhssaf_army_m10_digital_sq_lead","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_asst_mgun","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE"]]
	],0.2],
	// rhssaf_group_army_m10_digital_infantry_squad_sniper
	[[[["rhssaf_army_m10_digital_sq_lead","rhssaf_army_m10_digital_ft_lead","rhssaf_army_m10_digital_sniper_m76","rhssaf_army_m10_digital_asst_mgun","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_ft_lead","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]
	],0.2],
	// rhssaf_group_army_m10_digital_infantry_team
	[[[["rhssaf_army_m10_digital_ft_lead","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]
	],0.2],
	// rhssaf_group_army_m10_digital_infantry_team_mg
	[[[["rhssaf_army_m10_digital_ft_lead","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_asst_mgun"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.2],
	// rhssaf_group_army_m10_digital_infantry_team_AA
	[[[["rhssaf_army_m10_digital_ft_lead","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_spec_aa"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m10_digital_infantry_team_support
	[[[["rhssaf_army_m10_digital_ft_lead","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m10_digital_infantry_team_heavy_at
	[[[["rhssaf_army_m10_digital_ft_lead","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_gl","rhssaf_army_m10_digital_spec_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]
	],0.1],

	// rhssaf_group_army_m10_para_company_hq
	[[[["rhssaf_army_m10_para_officer","rhssaf_army_m10_para_officer","rhssaf_army_m10_para_sq_lead","rhssaf_army_m10_para_rifleman_g36"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["CAPTAIN","LIEUTENANT","SERGEANT","PRIVATE"]]
	],0.05],
	// rhssaf_group_army_m10_para_platoon_hq
	[[[["rhssaf_army_m10_para_officer","rhssaf_army_m10_para_sq_lead","rhssaf_army_m10_para_medic","rhssaf_army_m10_para_sq_lead","rhssaf_army_m10_para_rifleman_g36","rhssaf_army_m10_para_rifleman_hk416"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0]],["LIEUTENANT","SERGEANT","SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.05],
	// rhssaf_group_army_m10_para_infantry_squad
	[[[["rhssaf_army_m10_para_sq_lead","rhssaf_army_m10_para_ft_lead","rhssaf_army_m10_para_rifleman_m21","rhssaf_army_m10_para_mgun_m84","rhssaf_army_m10_para_gl_ag36","rhssaf_army_m10_para_ft_lead","rhssaf_army_m10_para_mgun_minimi","rhssaf_army_m10_para_gl_ag36","rhssaf_army_m10_para_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]
	],0.5],
	// rhssaf_group_army_m10_para_infantry_weaponsquad
	[[[["rhssaf_army_m10_para_sq_lead","rhssaf_army_m10_para_mgun_minimi","rhssaf_army_m10_para_asst_mgun_minimi","rhssaf_army_m10_para_gl_ag36","rhssaf_army_m10_para_mgun_m84","rhssaf_army_m10_para_asst_mgun_m84","rhssaf_army_m10_para_gl_m320","rhssaf_army_m10_para_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m10_para_infantry_squad_sniper
	[[[["rhssaf_army_m10_para_sq_lead","rhssaf_army_m10_para_ft_lead","rhssaf_army_m10_para_sniper_m76","rhssaf_army_m10_para_asst_mgun_m84","rhssaf_army_m10_para_sniper_m82a1","rhssaf_army_m10_para_ft_lead","rhssaf_army_m10_para_mgun_m84","rhssaf_army_m10_para_gl_ag36","rhssaf_army_m10_para_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0],[7,0,0],[9,0,0],[11,0,0],[13,0,0],[15,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL","PRIVATE","CORPORAL","PRIVATE","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m10_para_infantry_team
	[[[["rhssaf_army_m10_para_ft_lead","rhssaf_army_m10_para_mgun_minimi","rhssaf_army_m10_para_gl_m320","rhssaf_army_m10_para_rifleman_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m10_para_infantry_team_mg
	[[[["rhssaf_army_m10_para_ft_lead","rhssaf_army_m10_para_mgun_minimi","rhssaf_army_m10_para_gl_ag36","rhssaf_army_m10_para_asst_mgun_minimi"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.1],
	// rhssaf_group_army_m10_para_infantry_team_AA
	[[[["rhssaf_army_m10_para_ft_lead","rhssaf_army_m10_para_mgun_minimi","rhssaf_army_m10_para_gl_m320","rhssaf_army_m10_para_spec_aa"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.05],
	// rhssaf_group_army_m10_para_infantry_team_support
	[[[["rhssaf_army_m10_para_ft_lead","rhssaf_army_m10_para_mgun_m84","rhssaf_army_m10_para_gl_ag36","rhssaf_army_m10_para_medic"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","SERGEANT","PRIVATE","PRIVATE"]]
	],0.05],
	// rhssaf_group_army_m10_para_infantry_team_heavy_at
	[[[["rhssaf_army_m10_para_ft_lead","rhssaf_army_m10_para_mgun_minimi","rhssaf_army_m10_para_gl_m320","rhssaf_army_m10_para_spec_at"],[[0,5,0],[-5,0,0],[3,0,0],[5,0,0]],["SERGEANT","PRIVATE","PRIVATE","PRIVATE"]]
	],0.05],

	// rhssaf_group_army_motorized_infantry_team_hmg
	[[[["rhssaf_m1025_olive_m2","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_rifleman_at","rhssaf_army_m10_digital_gl"],[[0,0,0],[-12,-12,0],[14,-13,0],[5,0,0]],["SERGEANT","CORPORAL","PRIVATE","CORPORAL"]]
	],0.01],
	// rhssaf_group_army_motorized_infantry_team_at
	[[[["rhssaf_m1025_olive","rhssaf_army_m10_digital_spec_at","rhssaf_army_m10_digital_spec_at","rhssaf_army_m10_digital_asst_spec_at"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],["SERGEANT","CORPORAL","CORPORAL","PRIVATE"]]
	],0.01],
	// rhssaf_group_army_motorized_infantry_team_aa
	[[[["rhssaf_m1025_olive","rhssaf_army_m10_digital_mgun_m84","rhssaf_army_m10_digital_spec_aa","rhssaf_army_m10_digital_asst_spec_aa"],[[0,0,0],[13,-12,0],[-12,-13,0],[18,-17,-2]],["SERGEANT","CORPORAL","CORPORAL","PRIVATE"]]
	],0.01]
];
_arr append [
	// rhssaf_army_group_t72s_platoon
	[[[["rhssaf_army_t72s","rhssaf_army_t72s","rhssaf_army_t72s"],[[0,0,0],[20,-30,3],[-21,-30,3]],["LIEUTENANT","SERGEANT","SERGEANT"]]],0.1],
	// rhssaf_army_group_t72s_section
	[[[["rhssaf_army_t72s","rhssaf_army_t72s"],[[0,0,0],[20,-30,2]],["LIEUTENANT","SERGEANT"]]],0.1]
];
_arr = [_arr, _copyRef] call gosa_fnc_filtering_squads_byAvail_v2;
[_groups_map, resistance, "rhssaf_army", _arr,
	[1990,2100], [160,999],
	["IND_F","IND_E_F","IND_G_F","IND_C_F"]
] call gosa_fnc_map_groups_add;
