waitUntil {alive player};
player removeAction (player getVariable "_uav_action");
player setvariable ["_uav_action", nil];
player removeAction (player getVariable "_uav_heli_action");
player setvariable ["_uav_heli_action", nil];
player removeAction (player getVariable "_Buy_Man");
player setvariable ["_Buy_Man", nil];
player removeAction (player getVariable "_Buy_Ammo");
player setvariable ["_Buy_Ammo", nil];
player removeAction (player getVariable "_Buy_Car");
player setvariable ["_Buy_Car", nil];
player removeAction (player getVariable "_Buy_Motorcycle");
player setvariable ["_Buy_Motorcycle", nil];
player removeAction (player getVariable "_Buy_Tank");
player setvariable ["_Buy_Tank", nil];
player removeAction (player getVariable "_Buy_Helicopter");
player setvariable ["_Buy_Helicopter", nil];
player removeAction (player getVariable "_Buy_Plane");
player setvariable ["_Buy_Plane", nil];
player removeAction (player getVariable "_Buy_Support");
player setvariable ["_Buy_Support", nil];
player removeAction (player getVariable "_Buy_Ship");
player setvariable ["_Buy_Ship", nil];
player removeAction (player getVariable "_teleport_action");
player setvariable ["_teleport_action",nil];
player removeAction (player getVariable "_Buy_Pilot");
player setvariable ["_Buy_Pilot",nil];
player removeAction (player getVariable "_join_grpNull");
player setvariable ["_join_grpNull",nil];
