name: Upload Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: rsync sed rdfind liblingua-translit-perl transmission-cli ctorrent wget


      - name: depbo-tools get
        run: wget -O depbo-tools.tgz https://mikero.bytex.digital/api/download?filename=depbo-tools-0.10.13-linux-amd64.tgz
      - name: depbo-tools Extract
        run: tar -xf depbo*
      - name: depbo-tools rm tar
        run: find $PWD -maxdepth 1 -type f -name 'depbo*' -delete

      - name: depbo-tools Create package structure
        run: |
          mkdir -p mypackage/DEBIAN
          mkdir -p mypackage/usr/bin
          mkdir -p mypackage/usr/lib
      - name: depbo-tools mv bin
        run: mv depbo*/bin mypackage/usr/
      - name: depbo-tools mv lib
        run: mv depbo*/lib mypackage/usr/

      - name: depbo-tools Create control file
        run: |
          echo "Package: depbo-tools" > mypackage/DEBIAN/control
          echo "Version: 0.10.13" >> mypackage/DEBIAN/control
          echo "Section: base" >> mypackage/DEBIAN/control
          echo "Priority: optional" >> mypackage/DEBIAN/control
          echo "Architecture: amd64" >> mypackage/DEBIAN/control
          echo "Depends: libc6" >> mypackage/DEBIAN/control
          echo "Maintainer: in7j0 <205167430+in7j0@users.noreply.github.com>" >> mypackage/DEBIAN/control

      - name: depbo-tools Build deb package
        run: dpkg-deb --build mypackage
      - name: depbo-tools rm mypackage/
        run: depbo-tools rm -rf mypackage/
      - name: depbo-tools dpkg -i
        run: dpkg -i mypackage.deb


      - name: gosa checkout
        uses: actions/checkout@v4
      - name: gosa build
        run: bash ./tools/build_pbo_linux.sh -ltza

      - name: gosa clean
        run: rm -rf arma-glowing-octo-shame/*workshop*


      - name: GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: arma-glowing-octo-shame/*
