name: Upload Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: rsync sed rdfind liblingua-translit-perl transmission-cli ctorrent

      - name: curl depbo-tools
        uses: sozo-design/curl@v1.0.2
        with:
          args: -O https://mikero.bytex.digital/api/download?filename=depbo-tools-0.10.13-linux-amd64.tgz
      - name: Extract depbo-tools
        uses: a7ul/tar-action@v1.1.0
        id: extract
        with:
          command: x
          files: *.tgz

      - name: gosa checkout
        uses: actions/checkout@v4

      - name: Set Path
        run: |
          echo "/lib64/bin" >> $GITHUB_PATH
      - name: gosa build
        run: bash ./tools/build_pbo_linux.sh -ltza

      - name: gosa clean
        run: rm -rf arma-glowing-octo-shame/*workshop*

      - name: GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: arma-glowing-octo-shame/*
