name: Upload Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: rsync sed rdfind liblingua-translit-perl transmission-cli ctorrent wget

      - name: get depbo-tools
        run: wget -O depbo-tools.tgz https://mikero.bytex.digital/api/download?filename=depbo-tools-0.10.13-linux-amd64.tgz
      - name: Extract depbo-tools
        run: tar -xf depbo*

      - name: find PWD
        run: find $PWD

      - name: Set Path
        run: |
          echo "$PWD/depbo-tools/lib" >> "$GITHUB_PATH"
      - name: Set Path
        run: |
          echo "$PWD/depbo-tools/bin" >> "$GITHUB_PATH"

      - name: gosa checkout
        uses: actions/checkout@v4
      - name: gosa build
        run: bash ./tools/build_pbo_linux.sh -ltza

      - name: gosa clean
        run: rm -rf arma-glowing-octo-shame/*workshop*

      - name: GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: arma-glowing-octo-shame/*
