name: Upload Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: apt install
        run: |
          sudo add-apt-repository -S 'deb https://ppa.launchpadcontent.net/koffeinflummi/armake/ubuntu bionic main'
          sudo apt update
          sudo apt -y install rsync sed translit rdfind armake armake2 depbo-tools
      - name: Build
        run: ./tools/build_pbo_linux.sh -ltza
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: arma-glowing-octo-shame/*
